
package Views;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

public class Chronometer_View extends javax.swing.JFrame {
    
   private Timer t;
   private int h;
   private int m;
   private int s;
   // Como ActionListener es una clase abstracta se le tiene que definir lo que hace por eso el Override
   private ActionListener acciones = new ActionListener(){
       
       @Override
       public void actionPerformed(ActionEvent ae){
        ++ s;
        if(s >= 60){
            s = 0;
             ++ m;
        }
        if(m >= 60){
            m = 0;
             ++ h;
        }
        actualizarTexto();
    }
   };

    /**
     * Creates new form Cronometro
     * Estado inicial de la ventana
     */
    public Chronometer_View() {
        initComponents();
        setLocationRelativeTo(null);
        t = new Timer(1000, acciones);
        BtDetener.setEnabled(false);
        BtReiniciar.setEnabled(false);
    }
    
    public void actualizarTexto(){
        String newTime = h + ":" + m + ":" + s;
        LbTiempo.setText(newTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtIniciar = new javax.swing.JButton();
        BtDetener = new javax.swing.JButton();
        BtReiniciar = new javax.swing.JButton();
        LbTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtIniciar.setText("Iniciar");
        BtIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIniciarActionPerformed(evt);
            }
        });

        BtDetener.setText("Detener");
        BtDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDetenerActionPerformed(evt);
            }
        });

        BtReiniciar.setText("Reiniciar");
        BtReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtReiniciarActionPerformed(evt);
            }
        });

        LbTiempo.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        LbTiempo.setText("0:0:0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtDetener)
                        .addGap(86, 86, 86)
                        .addComponent(LbTiempo))
                    .addComponent(BtIniciar)
                    .addComponent(BtReiniciar))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(BtIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtDetener)
                    .addComponent(LbTiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtReiniciar)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIniciarActionPerformed
         t.start();
        BtIniciar.setEnabled(false);
        BtDetener.setEnabled(true);
        BtReiniciar.setEnabled(true);
    }//GEN-LAST:event_BtIniciarActionPerformed

    private void BtDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDetenerActionPerformed
       t.stop();
        BtIniciar.setEnabled(true);
        BtIniciar.setText("Reanudar");
    }//GEN-LAST:event_BtDetenerActionPerformed

    private void BtReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtReiniciarActionPerformed
        h = 0;
        m = 0;
        s = 0;
        t.start();
    }//GEN-LAST:event_BtReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Chronometer_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Chronometer_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Chronometer_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Chronometer_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Chronometer_View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtDetener;
    private javax.swing.JButton BtIniciar;
    private javax.swing.JButton BtReiniciar;
    private javax.swing.JLabel LbTiempo;
    // End of variables declaration//GEN-END:variables
}
